export const iconOptions = [
    { label: 'Ponsel', value: 'smartphone' },
    { label: 'Web/Dunia', value: 'globe' },
    { label: 'Edit/Gunting', value: 'scissors' },
    { label: 'Musik', value: 'music' },
    { label: 'Film', value: 'film' },
    { label: 'Desain/Palet', value: 'palette' },
    { label: 'AI/Otak', value: 'brain' },
    { label: 'YouTube/Play', value: 'youtube' },
    { label: 'TV', value: 'tv' },
    { label: 'Papan Film', value: 'clapperboard' },
    { label: 'Putar', value: 'play' },
    { label: 'Kilau', value: 'sparkles' },
    { label: 'Buku', value: 'book' },
    { label: 'Game/Gamepad', value: 'gamepad' },
    { label: 'Perang/Pedang', value: 'swords' },
    { label: 'Pemenang/Piala', value: 'trophy' },
    { label: 'Joystick', value: 'joystick' },
    { label: 'Target', value: 'target' },
    { label: 'Monitor', value: 'monitor' },
    { label: 'Kartu Kredit', value: 'card' },
    { label: 'Keranjang', value: 'cart' },
    { label: 'Cepat/Kilat', value: 'zap' },
    { label: 'Hati', value: 'heart' },
    { label: 'Hadiah', value: 'gift' },
    { label: 'Hantu', value: 'ghost' },
    { label: 'Crosshair', value: 'crosshair' },
    { label: 'Api', value: 'flame' },
    { label: 'Perisai', value: 'shield' },
    { label: 'Bintang', value: 'star' },
    { label: 'Mahkota', value: 'crown' },
    { label: 'Roket', value: 'rocket' },
];
